// Copyright Codevedas Inc. 2026-present
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.

#ifndef LAGHU_CONFIG_H
#define LAGHU_CONFIG_H

#include "laghu/core.h"

typedef enum {
  LAGHU_CONFIG_SETTING_UNKNOWN = 0,
  LAGHU_CONFIG_SETTING_PRESET,
  LAGHU_CONFIG_SETTING_REWRITE_LEVEL,
  LAGHU_CONFIG_SETTING_ENABLE_FILTER,
  LAGHU_CONFIG_SETTING_DISABLE_FILTER,
  LAGHU_CONFIG_SETTING_FORBID_FILTER,
  LAGHU_CONFIG_SETTING_ALLOW_RESOURCES,
  LAGHU_CONFIG_SETTING_DISALLOW_RESOURCES,
  LAGHU_CONFIG_SETTING_RESPECT_VARY,
  LAGHU_CONFIG_SETTING_RESPECT_FORWARDED_PROTO,
  LAGHU_CONFIG_SETTING_QUERY_FILTER_OVERRIDES,
  LAGHU_CONFIG_SETTING_ALLOW_API,
  LAGHU_CONFIG_SETTING_IMAGE_QUALITY,
  LAGHU_CONFIG_SETTING_IMAGE_BEACON,
  LAGHU_CONFIG_SETTING_CRITICAL_CSS_BEACON,
  LAGHU_CONFIG_SETTING_INSTRUMENTATION_BEACON,
  LAGHU_CONFIG_SETTING_OPTIMIZATION_PROFILES,
  LAGHU_CONFIG_SETTING_INSTRUMENTATION_SAMPLE_RATE,
  LAGHU_CONFIG_SETTING_JAVASCRIPT_DEFER_SUGGESTIONS,
  LAGHU_CONFIG_SETTING_INCLUDE_JS_SOURCE_MAPS,
  LAGHU_CONFIG_SETTING_IMAGE_INLINE_LIMIT,
  LAGHU_CONFIG_SETTING_IMAGE_METADATA_LIMIT,
  LAGHU_CONFIG_SETTING_IMAGE_METADATA_TTL,
  LAGHU_CONFIG_SETTING_CSS_INLINE_LIMIT,
  LAGHU_CONFIG_SETTING_CSS_OUTLINE_THRESHOLD,
  LAGHU_CONFIG_SETTING_JAVASCRIPT_INLINE_LIMIT,
  LAGHU_CONFIG_SETTING_JAVASCRIPT_OUTLINE_THRESHOLD,
  LAGHU_CONFIG_SETTING_TRANSFORM_MEMORY_LIMIT,
  LAGHU_CONFIG_SETTING_TRANSFORM_DEADLINE_MS,
  LAGHU_CONFIG_SETTING_VARIANTS_PER_SOURCE,
  LAGHU_CONFIG_SETTING_HTML_CACHE_ORIGIN,
  LAGHU_CONFIG_SETTING_HTML_CACHE_TTL,
  LAGHU_CONFIG_SETTING_HTML_CACHE_STALE_TTL,
  LAGHU_CONFIG_SETTING_CACHE_MIME_TYPES,
  LAGHU_CONFIG_SETTING_DOMAIN,
  LAGHU_CONFIG_SETTING_MAP_REWRITE_DOMAIN,
  LAGHU_CONFIG_SETTING_SHARD_DOMAIN,
  LAGHU_CONFIG_SETTING_MAP_PROXY_DOMAIN,
  LAGHU_CONFIG_SETTING_ROLLOUT,
  LAGHU_CONFIG_SETTING_ROLLOUT_PERCENTAGE,
  LAGHU_CONFIG_SETTING_ROLLOUT_PRESET,
  LAGHU_CONFIG_SETTING_ROLLOUT_REWRITE_LEVEL
} laghu_config_setting;

laghu_config_setting laghu_config_setting_find(const char *name);
bool laghu_config_setting_apply(laghu_config *config,
                                laghu_config_setting setting, const char *value,
                                char *error, size_t error_size);
/* MapRewriteDomain and MapProxyDomain retain their two migration arguments.
 * Single-value settings must use laghu_config_setting_apply instead. */
bool laghu_config_setting_apply_pair(laghu_config *config,
                                     laghu_config_setting setting,
                                     const char *first, const char *second,
                                     char *error, size_t error_size);

#endif
