# frozen_string_literal: true
# SPDX-License-Identifier: AGPL-3.0-only

# rubocop:disable Style/SignalException
valid_prefixes = %w[feat/ bugfix/ docs/ release/ chore/ refactor/ test/ style/ ci/ perf/ build/ lang/]

def all_modified_files(git)
  all_added = git.added_files + git.modified_files + git.renamed_files.map { |file| file[:after] }
  all_removed = git.deleted_files + git.renamed_files.map { |file| file[:before] }
  (all_added - all_removed).uniq
end

modified_files = all_modified_files(git)

fail('📝 Please include a more detailed description of your change.') if github.pr_body.strip.length < 10

if github.branch_for_head && valid_prefixes.none? { |prefix| github.branch_for_head.start_with?(prefix) }
  fail("⚠️ PR branch name should start with one of: #{valid_prefixes.join(', ')}")
end

# pr title should match with prefix minus / and colon
if github.pr_title && valid_prefixes.none? { |prefix| github.pr_title.start_with?("#{prefix.delete_suffix('/')}:") }
  fail("⚠️ PR title should start with one of: #{valid_prefixes.map { |p| "#{p.delete_suffix('/')}:" }.join(', ')}")
end

if github.branch_for_head&.start_with?('release/')
  changelog_modified = modified_files.include?('CHANGELOG.md')
  fail('🚨 CHANGELOG.md must be updated in a release branch.') unless changelog_modified
end

unless modified_files.grep(/\.rb$/).empty?
  test_files = modified_files.grep(%r{spec/|test/})
  warn('⚠️ No tests/specs modified. Please ensure tests are updated for any Ruby code changes.') if test_files.empty?
end

if violation_report[:errors].any? || violation_report[:warnings].any?
  message = <<~MSG
    ---
    ⚠️ You got #{violation_report[:errors].count} error(s) and #{violation_report[:warnings].count} warning(s) in your PR.
    🔧 **How to fix and re-trigger:**
    Please address the above issues and push your changes. The checks will automatically re-run on each push.
    If you want to manually re-run the checks on GitHub, you can do so from the "Actions" tab or the "Checks" section of this PR.
  MSG

  markdown(message)
end
# rubocop:enable Style/SignalException
