FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install --no-install-recommends -y \
      build-essential \
      bundler \
      clang-format \
      cmake \
      curl \
      libpcre2-dev \
      libssl-dev \
      ruby-dev \
      shellcheck \
      zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

CMD ["scripts/run-all"]

