# Copyright Codevedas Inc. 2026-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install --no-install-recommends -y \
      build-essential \
      bundler \
      clang-format \
      cmake \
      curl \
      libpcre2-dev \
      libssl-dev \
      libvips-dev \
      libvips-tools \
      ruby-dev \
      shellcheck \
      zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

CMD ["scripts/run-all"]
