# Copyright Codevedas Inc. 2026-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

<VirtualHost *:80>
  DocumentRoot /srv/corpus
  <Directory /srv/corpus>
    Require all granted
  </Directory>
  Laghu On
  Laghu RewriteLevel all
  Laghu Disallow /never-optimized/*
  <Location /no-store.html>
    Header set Cache-Control "no-store"
  </Location>
  <Location /private.html>
    Header set Cache-Control "private"
  </Location>
</VirtualHost>
