// Copyright Codevedas Inc. 2026-present
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.

use std::{env, fs, path::PathBuf};

fn value(value: &str) -> String {
    let value = value.trim().trim_end_matches('U').trim_end_matches('L');
    if let Some(value) = value
        .strip_prefix("UINT64_C(")
        .and_then(|value| value.strip_suffix(')'))
    {
        return value.to_owned();
    }
    value.to_owned()
}

fn main() {
    let contract = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap())
        .join("../../libs/laghu-runtime/persisted_state_contract.def");
    println!("cargo:rerun-if-changed={}", contract.display());
    let source = fs::read_to_string(&contract).expect("read persisted-state contract");
    let mut generated =
        String::from("// Generated by build.rs from persisted_state_contract.def.\n");
    for line in source.lines().map(str::trim) {
        for (macro_name, rust_type) in [
            ("LAGHU_PERSISTED_U32", "u32"),
            ("LAGHU_PERSISTED_U64", "u64"),
        ] {
            let Some(record) = line
                .strip_prefix(&format!("{macro_name}("))
                .and_then(|record| record.strip_suffix(')'))
            else {
                continue;
            };
            let (name, number) = record
                .split_once(',')
                .expect("persisted-state record must contain a name and value");
            generated.push_str(&format!(
                "pub const {name}: {rust_type} = {} as {rust_type};\n",
                value(number)
            ));
        }
    }
    fs::write(
        PathBuf::from(env::var("OUT_DIR").unwrap()).join("persisted_state.rs"),
        generated,
    )
    .expect("write generated persisted-state constants");
}
