#!/bin/sh
# Copyright Codevedas Inc. 2026-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

set -eu

rm -f /var/run/apache2/apache2.pid
a2enmod headers proxy proxy_http >/dev/null
sed -i 's/^Laghu Off$/Laghu On/' /etc/apache2/mods-available/laghu.conf
exec /usr/bin/mod-laghu-entrypoint
