#!/bin/sh
# Copyright Codevedas Inc. 2026-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

set -eu

rm -f /var/run/apache2/apache2.pid
a2enmod headers >/dev/null
sed -i 's/^Laghu Off$/Laghu On/' /etc/apache2/mods-available/laghu.conf
sed -i '/^Laghu Metrics On$/d; /^Laghu PurgeTokenFile \/etc\/laghu\/benchmark.token$/d; /^Laghu PurgeAllow 0\.0\.0\.0\/0$/d' \
  /etc/apache2/mods-available/laghu.conf
printf '%s\n' 'Laghu Metrics On' 'Laghu PurgeTokenFile /etc/laghu/benchmark.token' 'Laghu PurgeAllow 0.0.0.0/0' \
  >> /etc/apache2/mods-available/laghu.conf
exec /usr/bin/mod-laghu-entrypoint
