# Copyright Codevedas Inc. 2026-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

FROM python:3.13.2-slim-bookworm

RUN pip install --no-cache-dir --disable-pip-version-check \
      Pillow==11.1.0 scikit-image==0.25.1
COPY quality.py /usr/local/bin/laghu-image-quality
ENTRYPOINT ["python3", "/usr/local/bin/laghu-image-quality"]
