# Copyright Codevedas Inc. 2026-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

FROM node:22.15.0-bookworm

RUN apt-get update && apt-get install --no-install-recommends -y chromium && \
    npm install --global lighthouse@12.8.2 && \
    rm -rf /var/lib/apt/lists/*
ENTRYPOINT ["lighthouse"]
