# Copyright Codevedas Inc. 2026-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

load_module /usr/lib/nginx/modules/ngx_http_laghu_module.so;

daemon off;
pid /run/laghu/nginx.pid;
error_log /dev/stderr notice;

events {}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  access_log /dev/stdout;
  sendfile on;

  laghu on;
  laghu preset balanced;
  laghu image_quality 82;
  laghu worker_queue /run/laghu/jobs.queue;
  laghu image_cache /var/cache/laghu/images;

  server {
    listen 8080;
    root /usr/share/nginx/html;

    location / {
      try_files $uri $uri/ =404;
    }
  }
}
