load_module modules/ngx_http_laghu_module.so;

events {}

http {
  server {
    listen 8080;
    root /usr/share/nginx/html;

    laghu on;
    laghu preset balanced;

    location /api/ {
      laghu off;
    }
  }
}

