#!/bin/sh
# Copyright Codevedas Inc. 2026-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

set -eu

destination=/var/cache/plain-corpus
rm -rf "${destination:?}"/*
cp -a /srv/corpus/. "${destination}/"
find "${destination}" -type f \( -name '*.html' -o -name '*.css' -o -name '*.js' -o -name '*.svg' \) -print0 |
  xargs -0 -r gzip --no-name --keep --force --best
find "${destination}" -type f \( -name '*.html' -o -name '*.css' -o -name '*.js' -o -name '*.svg' \) -print0 |
  xargs -0 -r brotli --no-copy-stat --keep --force --quality=11
chmod -R a+rX "${destination}"

exec /usr/sbin/nginx -g 'daemon off;'
