# frozen_string_literal: true

# Copyright Codevedas Inc. 2026-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

source "https://rubygems.org"

gem "base64", "~> 0.3"
gem "bigdecimal", "~> 3.2"
gem "jekyll", "~> 3.10"
gem "kramdown-parser-gfm", "~> 1.1"
gem "webrick", "~> 1.9"

group :jekyll_plugins do
  gem "just-the-docs",
      git: "https://github.com/niteshpurohit/just-the-docs.git",
      ref: "933dc227584741c30a343cec25a1f315a3153988"
end
