# SPDX-License-Identifier: AGPL-3.0-only
if(NOT DEFINED HEADER OR NOT DEFINED CONFIG_JSON OR NOT DEFINED PROBE_JSON)
  message(FATAL_ERROR "Laghu capability parity expectation requires HEADER, CONFIG_JSON, and PROBE_JSON")
endif()
foreach(path IN ITEMS "${HEADER}" "${CONFIG_JSON}" "${PROBE_JSON}")
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "Laghu capability parity expectation failed: missing_output=${path}")
  endif()
endforeach()
file(READ "${HEADER}" header)
file(READ "${CONFIG_JSON}" config_json)
file(READ "${PROBE_JSON}" probe_json)
foreach(key IN ITEMS if_consteval expected byteswap to_underlying unreachable posix_baseline)
  if(NOT header MATCHES "inline constexpr bool has_${key} = (true|false);")
    message(FATAL_ERROR "Laghu capability parity expectation failed: missing_header_constant=${key}")
  endif()
  set(value "${CMAKE_MATCH_1}")
  foreach(metadata IN ITEMS "${config_json}" "${probe_json}")
    if(NOT metadata MATCHES "\"${key}\": ${value}")
      message(FATAL_ERROR "Laghu capability parity expectation failed: metadata_mismatch=${key}")
    endif()
  endforeach()
endforeach()
