# SPDX-License-Identifier: AGPL-3.0-only
if(NOT DEFINED MODE OR NOT DEFINED MODULE OR NOT DEFINED OUTPUT OR NOT DEFINED GOLDEN)
  message(FATAL_ERROR "Laghu capability render expectation requires MODE, MODULE, OUTPUT, and GOLDEN")
endif()

if(MODE STREQUAL "all_enabled")
  set(LAGHU_CAPABILITY_IF_CONSTEVAL true)
  set(LAGHU_CAPABILITY_EXPECTED true)
  set(LAGHU_CAPABILITY_BYTESWAP true)
  set(LAGHU_CAPABILITY_TO_UNDERLYING true)
  set(LAGHU_CAPABILITY_UNREACHABLE true)
  set(LAGHU_CAPABILITY_POSIX_BASELINE true)
elseif(MODE STREQUAL "baseline_unavailable")
  set(LAGHU_CAPABILITY_IF_CONSTEVAL true)
  set(LAGHU_CAPABILITY_EXPECTED true)
  set(LAGHU_CAPABILITY_BYTESWAP true)
  set(LAGHU_CAPABILITY_TO_UNDERLYING true)
  set(LAGHU_CAPABILITY_UNREACHABLE true)
  set(LAGHU_CAPABILITY_POSIX_BASELINE false)
else()
  message(FATAL_ERROR "Laghu capability render expectation failed: unknown_mode=${MODE}")
endif()

include("${MODULE}")
laghu_generate_capability_header("${OUTPUT}")
file(READ "${OUTPUT}" rendered)
file(READ "${GOLDEN}" expected)
if(NOT rendered STREQUAL expected)
  message(FATAL_ERROR "Laghu capability render expectation failed: golden_mismatch mode=${MODE}")
endif()

set(repeated_output "${OUTPUT}.repeated")
laghu_generate_capability_header("${repeated_output}")
file(SHA256 "${OUTPUT}" rendered_digest)
file(SHA256 "${repeated_output}" repeated_digest)
file(REMOVE "${repeated_output}")
if(NOT rendered_digest STREQUAL repeated_digest)
  message(FATAL_ERROR "Laghu capability render expectation failed: nondeterministic mode=${MODE}")
endif()
