# SPDX-License-Identifier: AGPL-3.0-only

if(NOT DEFINED MANIFEST OR NOT DEFINED PREIMAGE OR NOT DEFINED LAGHU_SOURCE OR NOT DEFINED LAGHU_BINARY)
  message(FATAL_ERROR "Laghu build identity expectation requires MANIFEST, PREIMAGE, LAGHU_SOURCE, and LAGHU_BINARY")
endif()
foreach(path IN ITEMS "${MANIFEST}" "${PREIMAGE}")
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "Laghu build identity expectation failed: missing_output=${path}")
  endif()
endforeach()

file(READ "${MANIFEST}" manifest)
file(READ "${PREIMAGE}" preimage)
string(STRIP "${manifest}" manifest)
string(STRIP "${preimage}" preimage)
string(JSON schema_version GET "${manifest}" schema_version)
string(JSON product_name GET "${manifest}" product name)
string(JSON product_version GET "${manifest}" product version)
string(JSON build_id GET "${manifest}" build_id)
if(NOT schema_version STREQUAL "laghu-build-manifest-v1" OR NOT product_name STREQUAL "laghu" OR
    NOT product_version STREQUAL "0.0.1")
  message(FATAL_ERROR "Laghu build identity expectation failed: product_or_schema_invalid")
endif()
string(SHA256 preimage_id "${preimage}")
if(NOT build_id STREQUAL preimage_id)
  message(FATAL_ERROR "Laghu build identity expectation failed: build_id_preimage_mismatch")
endif()
string(JSON input_count LENGTH "${manifest}" build_inputs)
if(input_count LESS 1)
  message(FATAL_ERROR "Laghu build identity expectation failed: build_inputs_missing")
endif()
math(EXPR input_last "${input_count} - 1")
foreach(index RANGE ${input_last})
  string(JSON input_path GET "${manifest}" build_inputs ${index} path)
  string(JSON input_sha256 GET "${manifest}" build_inputs ${index} sha256)
  string(LENGTH "${input_sha256}" input_sha256_length)
  if(input_path MATCHES "^/" OR input_path MATCHES "^[A-Za-z]:" OR
      NOT input_sha256_length EQUAL 64 OR NOT input_sha256 MATCHES "^[0-9a-f]+$")
    message(FATAL_ERROR "Laghu build identity expectation failed: declared_input_not_canonical index=${index}")
  endif()
endforeach()
foreach(forbidden IN ITEMS "${LAGHU_SOURCE}" "${LAGHU_BINARY}" "timestamp" "hostname" "username")
  string(FIND "${manifest}" "${forbidden}" forbidden_offset)
  if(NOT forbidden_offset EQUAL -1)
    message(FATAL_ERROR "Laghu build identity expectation failed: forbidden_value=${forbidden}")
  endif()
endforeach()
string(JSON dependency_count LENGTH "${manifest}" dependencies)
string(JSON effective_feature_count LENGTH "${manifest}" features effective)
string(JSON first_effective_feature GET "${manifest}" features effective 0)
if(effective_feature_count EQUAL 1 AND first_effective_feature STREQUAL "core")
  if(NOT dependency_count EQUAL 0)
    message(FATAL_ERROR "Laghu build identity expectation failed: minimal_dependencies_not_empty")
  endif()
  if(manifest MATCHES "tls_provider|link_mode|dependency_source")
    message(FATAL_ERROR "Laghu build identity expectation failed: disabled_selector_present")
  endif()
elseif(dependency_count EQUAL 0)
  message(FATAL_ERROR "Laghu build identity expectation failed: enabled_dependencies_missing")
endif()

if(DEFINED RUN_CLI AND RUN_CLI)
  if(NOT DEFINED CLI OR NOT EXISTS "${CLI}")
    message(FATAL_ERROR "Laghu build identity expectation failed: cli_missing")
  endif()
  execute_process(COMMAND "${CLI}" version RESULT_VARIABLE plain_result OUTPUT_VARIABLE plain_output ERROR_VARIABLE plain_error)
  if(NOT plain_result EQUAL 0 OR NOT plain_output STREQUAL "laghu 0.0.1\n" OR NOT plain_error STREQUAL "")
    message(FATAL_ERROR "Laghu build identity expectation failed: plain_version_invalid")
  endif()
  execute_process(COMMAND "${CLI}" version --json RESULT_VARIABLE json_result OUTPUT_VARIABLE json_output ERROR_VARIABLE json_error)
  if(NOT json_result EQUAL 0 OR NOT json_output STREQUAL "${manifest}\n" OR NOT json_error STREQUAL "")
    message(FATAL_ERROR "Laghu build identity expectation failed: json_version_invalid")
  endif()
  execute_process(COMMAND "${CLI}" version --verbose RESULT_VARIABLE verbose_result OUTPUT_VARIABLE verbose_output ERROR_VARIABLE verbose_error)
  if(NOT verbose_result EQUAL 0 OR NOT verbose_error STREQUAL "")
    message(FATAL_ERROR "Laghu build identity expectation failed: verbose_version_invalid")
  endif()
  string(REPLACE "\n" ";" verbose_lines "${verbose_output}")
  list(POP_BACK verbose_lines trailing_line)
  set(sorted_lines ${verbose_lines})
  list(SORT sorted_lines)
  string(FIND "${verbose_output}" "build_id=${build_id}\n" build_id_offset)
  if(NOT verbose_lines STREQUAL sorted_lines OR NOT build_id_offset EQUAL 0)
    message(FATAL_ERROR "Laghu build identity expectation failed: verbose_output_not_sorted")
  endif()
  execute_process(COMMAND "${CLI}" invalid RESULT_VARIABLE invalid_result OUTPUT_VARIABLE invalid_output ERROR_VARIABLE invalid_error)
  if(NOT invalid_result EQUAL 2 OR NOT invalid_output STREQUAL "" OR
      NOT invalid_error STREQUAL "usage: laghu version [--verbose|--json]\n")
    message(FATAL_ERROR "Laghu build identity expectation failed: invalid_usage_invalid")
  endif()
endif()
