# SPDX-License-Identifier: AGPL-3.0-only
if(NOT DEFINED MANIFEST)
  message(FATAL_ERROR "Laghu warning suppression expectation requires MANIFEST")
endif()
file(STRINGS "${MANIFEST}" lines)
foreach(line IN LISTS lines)
  if(line MATCHES "^[ \t]*#" OR line STREQUAL "")
    continue()
  endif()
  string(REPLACE "\t" ";" fields "${line}")
  list(LENGTH fields field_count)
  if(NOT field_count EQUAL 4)
    message(STATUS "Laghu warning suppression rejected: malformed entry")
    return()
  endif()
  list(GET fields 0 source)
  list(GET fields 1 warning)
  list(GET fields 3 reason)
  if(NOT source MATCHES "^src/(core|config|protocol|tls|proxy|cache|control|cli|observability|os)/[A-Za-z0-9_./-]+\\.(cpp|cc|cxx)$")
    message(STATUS "Laghu warning suppression rejected: broad source=${source}")
    return()
  endif()
  if(NOT warning MATCHES "^-Wno-(conversion|sign-conversion|shadow|format|format-security|null-dereference|double-promotion|implicit-fallthrough|cast-align|cast-qual|old-style-cast|overloaded-virtual|non-virtual-dtor|zero-as-null-pointer-constant|undef|uninitialized|arith-conversion|dangling-pointer|format-overflow|format-truncation|array-bounds|stringop-overflow|duplicated-cond|logical-op|useless-cast|shadow-all|implicit-int-conversion|shorten-64-to-32|dangling|unsafe-buffer-usage)$")
    message(STATUS "Laghu warning suppression rejected: invalid warning=${warning}")
    return()
  endif()
  if(reason STREQUAL "")
    message(STATUS "Laghu warning suppression rejected: missing technical reason")
    return()
  endif()
endforeach()
message(FATAL_ERROR "Laghu warning suppression expectation failed: manifest unexpectedly passed")
