# SPDX-License-Identifier: AGPL-3.0-only

if(NOT DEFINED METADATA OR NOT DEFINED LAGHU_SOURCE OR NOT DEFINED LAGHU_BINARY)
  message(FATAL_ERROR "Laghu dependency selection metadata expectation requires METADATA, LAGHU_SOURCE, and LAGHU_BINARY")
endif()
if(NOT EXISTS "${METADATA}")
  message(FATAL_ERROR "Laghu dependency selection metadata expectation failed: missing_output=${METADATA}")
endif()
file(READ "${METADATA}" metadata)
foreach(requirement IN ITEMS
    "\"schema_version\": \"laghu-dependency-selection-v1\""
    "\"active_dependencies\": [")
  string(FIND "${metadata}" "${requirement}" requirement_offset)
  if(requirement_offset EQUAL -1)
    message(FATAL_ERROR "Laghu dependency selection metadata expectation failed: missing_requirement=${requirement}")
  endif()
endforeach()
string(JSON active_dependency_count LENGTH "${metadata}" active_dependencies)
if(active_dependency_count EQUAL 0)
  foreach(selector IN ITEMS source link_mode tls_provider)
    string(FIND "${metadata}" "\"${selector}\":" selector_offset)
    if(NOT selector_offset EQUAL -1)
      message(FATAL_ERROR "Laghu dependency selection metadata expectation failed: inactive_selector_recorded=${selector}")
    endif()
  endforeach()
else()
  foreach(selector IN ITEMS source link_mode tls_provider)
    string(FIND "${metadata}" "\"${selector}\":" selector_offset)
    if(selector_offset EQUAL -1)
      message(FATAL_ERROR "Laghu dependency selection metadata expectation failed: active_selector_missing=${selector}")
    endif()
  endforeach()
  math(EXPR active_dependency_last "${active_dependency_count} - 1")
  foreach(index RANGE ${active_dependency_last})
    foreach(field IN ITEMS id source link_mode version archive_url archive_sha256)
      string(JSON value ERROR_VARIABLE json_error GET
        "${metadata}" active_dependencies ${index} ${field})
      if(json_error OR value STREQUAL "")
        message(FATAL_ERROR "Laghu dependency selection metadata expectation failed: dependency_field_missing=${field}")
      endif()
    endforeach()
  endforeach()
endif()
if(metadata MATCHES "${LAGHU_SOURCE}" OR metadata MATCHES "${LAGHU_BINARY}")
  message(FATAL_ERROR "Laghu dependency selection metadata expectation failed: filesystem_path_leak")
endif()
