# SPDX-License-Identifier: AGPL-3.0-only
if(NOT DEFINED CONFIG OR NOT DEFINED MANIFEST OR NOT DEFINED LAGHU_SOURCE OR NOT DEFINED LAGHU_BINARY)
  message(FATAL_ERROR "Laghu hardening metadata expectation requires CONFIG MANIFEST LAGHU_SOURCE and LAGHU_BINARY")
endif()

foreach(path IN ITEMS "${CONFIG}" "${MANIFEST}")
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "Laghu hardening metadata expectation failed: output=missing")
  endif()
  file(READ "${path}" document)
  string(JSON mode GET "${document}" hardening mode)
  foreach(feature IN ITEMS pie stack_protection relro immediate_binding fortification)
    string(JSON supported TYPE "${document}" hardening ${feature} supported)
    string(JSON enabled TYPE "${document}" hardening ${feature} enabled)
    string(JSON state GET "${document}" hardening ${feature} state)
    if(NOT "${supported}" STREQUAL "BOOLEAN" OR NOT "${enabled}" STREQUAL "BOOLEAN" OR
        (NOT "${state}" STREQUAL "supported" AND NOT "${state}" STREQUAL "unsupported"))
      message(FATAL_ERROR "Laghu hardening metadata expectation failed: feature=${feature}; schema=invalid")
    endif()
    string(JSON supported_value GET "${document}" hardening ${feature} supported)
    string(JSON enabled_value GET "${document}" hardening ${feature} enabled)
    if("${enabled_value}" STREQUAL "ON" AND "${supported_value}" STREQUAL "OFF")
      message(FATAL_ERROR "Laghu hardening metadata expectation failed: feature=${feature}; enabled_without_support")
    endif()
    if("${mode}" STREQUAL "Release" AND "${supported_value}" STREQUAL "ON" AND
       "${enabled_value}" STREQUAL "OFF")
      message(FATAL_ERROR "Laghu hardening metadata expectation failed: feature=${feature}; supported_not_enabled")
    endif()
    if("${state}" STREQUAL "unsupported" AND
       ("${supported_value}" STREQUAL "ON" OR "${enabled_value}" STREQUAL "ON"))
      message(FATAL_ERROR "Laghu hardening metadata expectation failed: feature=${feature}; unsupported_state_invalid")
    endif()
  endforeach()
  foreach(forbidden IN ITEMS "${LAGHU_SOURCE}" "${LAGHU_BINARY}" timestamp hostname username)
    string(FIND "${document}" "${forbidden}" offset)
    if(NOT offset EQUAL -1)
      message(FATAL_ERROR "Laghu hardening metadata expectation failed: forbidden_value=present")
    endif()
  endforeach()
endforeach()
