# SPDX-License-Identifier: AGPL-3.0-only
if(NOT DEFINED LIBRARY OR NOT DEFINED NM OR NOT DEFINED PLATFORM)
  message(FATAL_ERROR "Laghu symbol inspection requires LIBRARY, NM, and PLATFORM")
endif()
if(NOT EXISTS "${LIBRARY}")
  message(FATAL_ERROR "Laghu symbol inspection is missing library=${LIBRARY}")
endif()
if(PLATFORM STREQUAL "Darwin")
  set(nm_arguments -gU "${LIBRARY}")
else()
  set(nm_arguments -D --defined-only "${LIBRARY}")
endif()
execute_process(
  COMMAND "${NM}" ${nm_arguments}
  RESULT_VARIABLE result OUTPUT_VARIABLE symbols ERROR_VARIABLE diagnostics)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Laghu symbol inspection failed: library=${LIBRARY}\n${diagnostics}")
endif()
set(found_laghu_symbol FALSE)
if(symbols MATCHES "(_+)?ZN5laghu|laghu::|laghu_")
  set(found_laghu_symbol TRUE)
endif()
if(DEFINED EXPECT_FAIL AND EXPECT_FAIL)
  if(NOT found_laghu_symbol)
    message(FATAL_ERROR "Laghu symbol inspection expected an exported implementation symbol: ${LIBRARY}")
  endif()
elseif(found_laghu_symbol)
  message(FATAL_ERROR "Laghu symbol inspection found exported implementation symbol(s):\n${symbols}")
endif()
