# SPDX-License-Identifier: AGPL-3.0-only
if(NOT DEFINED SOURCE OR NOT DEFINED EXPECT_RULE)
  message(FATAL_ERROR "Laghu profile expectation requires SOURCE and EXPECT_RULE")
endif()
file(READ "${SOURCE}" contents)
set(pattern)
if(EXPECT_RULE STREQUAL exceptions)
  set(pattern "(throw|try|catch)")
elseif(EXPECT_RULE STREQUAL rtti)
  set(pattern "(dynamic_cast|typeid|std::type_info|type_info)")
elseif(EXPECT_RULE STREQUAL coroutines)
  set(pattern "(co_await|co_return|co_yield|coroutine)")
elseif(EXPECT_RULE STREQUAL futures)
  set(pattern "(future|shared_future|promise|async|packaged_task)")
elseif(EXPECT_RULE STREQUAL iostream)
  set(pattern "iostream")
elseif(EXPECT_RULE STREQUAL virtual)
  set(pattern "virtual")
else()
  message(FATAL_ERROR "Laghu profile expectation has unknown rule=${EXPECT_RULE}")
endif()
if(NOT contents MATCHES "(^|[^A-Za-z0-9_])(${pattern})([^A-Za-z0-9_]|$)")
  message(FATAL_ERROR "Laghu profile expectation failed: rule=${EXPECT_RULE} source=${SOURCE}")
endif()
