# SPDX-License-Identifier: AGPL-3.0-only
if(NOT DEFINED CXX OR NOT DEFINED SOURCE OR NOT DEFINED EXPECT_FAIL)
  message(FATAL_ERROR "Laghu compile expectation requires CXX, SOURCE, and EXPECT_FAIL")
endif()
if(NOT DEFINED STANDARD)
  set(STANDARD c++23)
endif()
if(NOT DEFINED FLAGS)
  set(FLAGS)
endif()
if(DEFINED CXXFLAGS)
  separate_arguments(cxxflags NATIVE_COMMAND "${CXXFLAGS}")
else()
  set(cxxflags)
endif()
if(DEFINED INCLUDE_DIRECTORIES)
  set(include_flags)
  foreach(include_directory IN LISTS INCLUDE_DIRECTORIES)
    list(APPEND include_flags "-I${include_directory}")
  endforeach()
else()
  set(include_flags)
endif()
execute_process(
  COMMAND "${CXX}" "-std=${STANDARD}" ${cxxflags} -pedantic-errors ${FLAGS} ${include_flags} -c "${SOURCE}" -o "${CMAKE_CURRENT_BINARY_DIR}/expect-compile.o"
  RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
set(diagnostics "${stdout}${stderr}")
if(EXPECT_FAIL)
  if(result EQUAL 0)
    message(FATAL_ERROR "Laghu compile expectation failed: expected_failure source=${SOURCE}")
  endif()
  if(DEFINED EXPECT_TEXT AND NOT diagnostics MATCHES "${EXPECT_TEXT}")
    message(FATAL_ERROR "Laghu compile expectation failed: missing_diagnostic=${EXPECT_TEXT}")
  endif()
elseif(NOT result EQUAL 0)
  message(FATAL_ERROR "Laghu compile expectation failed: expected_success source=${SOURCE}\n${diagnostics}")
endif()
