# SPDX-License-Identifier: AGPL-3.0-only
include_guard(GLOBAL)

include("${CMAKE_CURRENT_LIST_DIR}/LaghuDependencyDag.cmake")

function(laghu_api_boundary_fail rule detail)
  message(FATAL_ERROR "Laghu API boundary failed: rule=${rule} ${detail}")
endfunction()

function(laghu_api_source_root output)
  if(DEFINED LAGHU_SOURCE AND NOT LAGHU_SOURCE STREQUAL "")
    set(${output} "${LAGHU_SOURCE}" PARENT_SCOPE)
  else()
    set(${output} "${CMAKE_SOURCE_DIR}" PARENT_SCOPE)
  endif()
endfunction()

function(laghu_api_require_node node detail)
  list(FIND LAGHU_SUBSYSTEM_NODES "${node}" node_index)
  if(node_index EQUAL -1)
    laghu_api_boundary_fail(header_subsystem "subsystem=${node} ${detail}")
  endif()
endfunction()

function(laghu_api_header_details header output_node output_kind output_relative)
  laghu_api_source_root(source_root)
  file(RELATIVE_PATH relative_header "${source_root}" "${header}")
  string(REPLACE "\\" "/" relative_header "${relative_header}")
  if(relative_header MATCHES "^src/([^/]+)/contract/laghu/([^/]+)/.+\\.(hpp|hh|hxx)$")
    set(node "${CMAKE_MATCH_1}")
    set(namespace_node "${CMAKE_MATCH_2}")
    set(kind contract)
  elseif(relative_header MATCHES "^src/([^/]+)/private/laghu/([^/]+)/internal/.+\\.(hpp|hh|hxx)$")
    set(node "${CMAKE_MATCH_1}")
    set(namespace_node "${CMAKE_MATCH_2}")
    set(kind private)
  else()
    laghu_api_boundary_fail(header_layout "file=${relative_header}; expected=src/subsystem/(contract|private)/laghu/subsystem")
  endif()
  if(NOT node STREQUAL namespace_node)
    laghu_api_boundary_fail(header_layout "file=${relative_header}; path_subsystem=${node} namespace_subsystem=${namespace_node}")
  endif()
  laghu_api_require_node("${node}" "file=${relative_header}")
  set(${output_node} "${node}" PARENT_SCOPE)
  set(${output_kind} "${kind}" PARENT_SCOPE)
  set(${output_relative} "${relative_header}" PARENT_SCOPE)
endfunction()

function(laghu_api_validate_header_file header node kind)
  file(READ "${header}" contents)
  if(kind STREQUAL "contract")
    if(NOT contents MATCHES "namespace[ \t\r\n]+laghu::${node}[ \t\r\n{]")
      laghu_api_boundary_fail(contract_namespace "file=${header}; expected=laghu::${node}")
    endif()
    if(contents MATCHES "#[ \t]*include[ \t]*[<\"][^>\"]+\\.h[>\"]")
      laghu_api_boundary_fail(external_c_header "file=${header}; contract_headers_may_not_include_c_headers")
    endif()
    if(contents MATCHES "(^|[^A-Za-z0-9_])(FILE|DIR|sockaddr|sockaddr_storage|socklen_t|pid_t|ssize_t|nfds_t|time_t|fd_set)([^A-Za-z0-9_]|$)")
      laghu_api_boundary_fail(external_c_type "file=${header}; contract_headers_may_not_expose_c_or_posix_types")
    endif()
  elseif(kind STREQUAL "private")
    if(NOT contents MATCHES "namespace[ \t\r\n]+laghu::${node}::internal[ \t\r\n{]")
      laghu_api_boundary_fail(private_namespace "file=${header}; expected=laghu::${node}::internal")
    endif()
  else()
    laghu_api_boundary_fail(header_kind "file=${header}; kind=${kind}")
  endif()

  string(REGEX MATCHALL "#[ \t]*include[ \t]*[<\"]laghu/[A-Za-z0-9_]+/[^>\"]+[>\"]" laghu_includes "${contents}")
  foreach(laghu_include IN LISTS laghu_includes)
    string(REGEX REPLACE ".*laghu/([A-Za-z0-9_]+)/.*" "\\1" include_node "${laghu_include}")
    if(laghu_include MATCHES "/internal/")
      if(NOT kind STREQUAL "private" OR NOT include_node STREQUAL node)
        laghu_api_boundary_fail(private_header_leak "file=${header}; include=${laghu_include}")
      endif()
    elseif(NOT include_node STREQUAL node)
      get_property(allowed_providers GLOBAL PROPERTY "LAGHU_DAG_ALLOWED_${node}")
      list(FIND allowed_providers "${include_node}" allowed_index)
      if(allowed_index EQUAL -1)
        laghu_api_boundary_fail(contract_dependency "file=${header}; consumer=${node} provider=${include_node} rule=edge_not_allowed")
      endif()
    endif()
  endforeach()
endfunction()

function(laghu_validate_api_header header)
  laghu_api_header_details("${header}" node kind relative_header)
  laghu_api_validate_header_file("${header}" "${node}" "${kind}")
endfunction()

function(laghu_validate_implementation_source source)
  file(READ "${source}" contents)
  if(contents MATCHES "laghu_core_contract")
    laghu_api_boundary_fail(legacy_global_symbol "file=${source}; symbol=laghu_core_contract")
  endif()
endfunction()

function(laghu_validate_private_header_ownership source node)
  file(READ "${source}" contents)
  if(contents MATCHES "#[ \t]*include[ \t]*[<\"][^>\"]*private/laghu/")
    laghu_api_boundary_fail(private_header_direct_path "file=${source}; use=laghu/subsystem/internal/header.hpp")
  endif()
  string(REGEX MATCHALL "#[ \t]*include[ \t]*[<\"]laghu/[A-Za-z0-9_]+/internal/[^>\"]+[>\"]" private_includes "${contents}")
  foreach(private_include IN LISTS private_includes)
    string(REGEX REPLACE ".*laghu/([A-Za-z0-9_]+)/internal/.*" "\\1" include_node "${private_include}")
    if(NOT include_node STREQUAL node)
      laghu_api_boundary_fail(private_header_owner "file=${source}; consumer=${node} provider=${include_node}")
    endif()
  endforeach()
endfunction()

function(laghu_configure_api_boundaries)
  laghu_api_source_root(source_root)
  if(IS_DIRECTORY "${source_root}/include")
    laghu_api_boundary_fail(no_public_include_root "directory=include")
  endif()
  file(GLOB_RECURSE headers CONFIGURE_DEPENDS
    "${source_root}/src/*.hpp" "${source_root}/src/*.hh" "${source_root}/src/*.hxx")
  foreach(header IN LISTS headers)
    laghu_validate_api_header("${header}")
  endforeach()
  if(NOT EXISTS "${source_root}/src/core/contract/laghu/core/contract.hpp")
    laghu_api_boundary_fail(required_core_contract "file=src/core/contract/laghu/core/contract.hpp")
  endif()
  if(NOT EXISTS "${source_root}/src/core/private/laghu/core/internal/compiler_extensions.hpp")
    laghu_api_boundary_fail(required_core_private_header "file=src/core/private/laghu/core/internal/compiler_extensions.hpp")
  endif()
  file(GLOB_RECURSE implementation_sources CONFIGURE_DEPENDS
    "${source_root}/src/*.cpp" "${source_root}/src/*.cc" "${source_root}/src/*.cxx")
  foreach(source IN LISTS implementation_sources)
    laghu_validate_implementation_source("${source}")
    file(RELATIVE_PATH relative_source "${source_root}/src" "${source}")
    if(relative_source MATCHES "^([^/]+)/")
      laghu_validate_private_header_ownership("${source}" "${CMAKE_MATCH_1}")
    endif()
  endforeach()
  set(LAGHU_API_HEADERS "${headers}" CACHE INTERNAL "Laghu internal API headers")
  target_include_directories(laghu_core PRIVATE
    "${source_root}/src/core/private"
    "${source_root}/src/core/contract"
    "${CMAKE_BINARY_DIR}/generated")
endfunction()

function(laghu_api_header_include_directories header output)
  laghu_api_source_root(source_root)
  laghu_api_header_details("${header}" node kind relative_header)
  set(include_directories "${source_root}/src/${node}/contract")
  if(kind STREQUAL "private")
    list(PREPEND include_directories "${source_root}/src/${node}/private")
  endif()
  get_property(allowed_providers GLOBAL PROPERTY "LAGHU_DAG_ALLOWED_${node}")
  foreach(provider IN LISTS allowed_providers)
    if(IS_DIRECTORY "${source_root}/src/${provider}/contract")
      list(APPEND include_directories "${source_root}/src/${provider}/contract")
    endif()
  endforeach()
  list(REMOVE_DUPLICATES include_directories)
  set(${output} "${include_directories}" PARENT_SCOPE)
endfunction()

function(laghu_api_header_test_name header output)
  laghu_api_source_root(source_root)
  file(RELATIVE_PATH relative_header "${source_root}/src" "${header}")
  string(REPLACE "/" "." test_name "${relative_header}")
  string(REPLACE ".hpp" "" test_name "${test_name}")
  string(REPLACE ".hh" "" test_name "${test_name}")
  string(REPLACE ".hxx" "" test_name "${test_name}")
  set(${output} "${test_name}" PARENT_SCOPE)
endfunction()

function(laghu_api_header_include_name header output)
  laghu_api_source_root(source_root)
  file(RELATIVE_PATH relative_header "${source_root}/src" "${header}")
  if(relative_header MATCHES "^[^/]+/(contract|private)/(.+)$")
    set(${output} "${CMAKE_MATCH_2}" PARENT_SCOPE)
  else()
    laghu_api_boundary_fail(header_layout "file=${relative_header}")
  endif()
endfunction()

function(laghu_configure_api_consumer target node)
  laghu_api_source_root(source_root)
  laghu_api_require_node("${node}" "target=${target}")
  set(include_directories "${source_root}/src/${node}/contract")
  get_property(allowed_providers GLOBAL PROPERTY "LAGHU_DAG_ALLOWED_${node}")
  foreach(provider IN LISTS allowed_providers)
    if(IS_DIRECTORY "${source_root}/src/${provider}/contract")
      list(APPEND include_directories "${source_root}/src/${provider}/contract")
    endif()
  endforeach()
  target_include_directories("${target}" PRIVATE ${include_directories})
endfunction()

function(laghu_add_visibility_probe)
  add_library(laghu_visibility_probe SHARED
    src/core/contract.cpp
    src/core/digest.cpp
    src/core/fingerprints.cpp
    src/core/handles.cpp
    src/core/mapped_regions.cpp)
  laghu_apply_first_party_contract(laghu_visibility_probe)
  laghu_configure_api_consumer(laghu_visibility_probe core)
  laghu_api_source_root(source_root)
  target_include_directories(laghu_visibility_probe PRIVATE
    "${source_root}/src/core/private"
    "${CMAKE_BINARY_DIR}/generated")
endfunction()
