# SPDX-License-Identifier: AGPL-3.0-only
include_guard(GLOBAL)

function(laghu_hardening_fail detail)
  message(FATAL_ERROR "Laghu hardening configuration failed: ${detail}")
endfunction()

function(laghu_hardening_probe feature output)
  cmake_parse_arguments(PROBE "" "SOURCE" "COMPILE_OPTIONS;LINK_OPTIONS" ${ARGN})
  if(NOT DEFINED PROBE_SOURCE OR PROBE_SOURCE STREQUAL "")
    set(PROBE_SOURCE "${CMAKE_SOURCE_DIR}/tests/hardening/probes/clean.cpp")
  endif()
  if(DEFINED CMAKE_TRY_COMPILE_TARGET_TYPE)
    set(had_try_compile_target_type true)
    set(saved_try_compile_target_type "${CMAKE_TRY_COMPILE_TARGET_TYPE}")
  else()
    set(had_try_compile_target_type false)
  endif()
  if(PROBE_LINK_OPTIONS)
    set(CMAKE_TRY_COMPILE_TARGET_TYPE EXECUTABLE)
  endif()
  try_compile(result "${CMAKE_BINARY_DIR}/probes/try-hardening-${feature}"
    SOURCES "${PROBE_SOURCE}"
    COMPILE_DEFINITIONS ${PROBE_COMPILE_OPTIONS}
    LINK_OPTIONS ${PROBE_LINK_OPTIONS}
    CMAKE_FLAGS
      "-DCMAKE_CXX_STANDARD=23"
      "-DCMAKE_CXX_STANDARD_REQUIRED=ON"
      "-DCMAKE_CXX_EXTENSIONS=OFF"
      "-DCMAKE_CXX_SCAN_FOR_MODULES=OFF"
    OUTPUT_VARIABLE probe_output)
  if(had_try_compile_target_type)
    set(CMAKE_TRY_COMPILE_TARGET_TYPE "${saved_try_compile_target_type}")
  else()
    unset(CMAKE_TRY_COMPILE_TARGET_TYPE)
  endif()
  laghu_sanitize_probe_text(sanitized_output "${probe_output}")
  file(WRITE "${CMAKE_BINARY_DIR}/probes/hardening-${feature}.log" "${sanitized_output}")
  if(result)
    set(${output} true PARENT_SCOPE)
  else()
    set(${output} false PARENT_SCOPE)
  endif()
endfunction()

function(laghu_hardening_feature_json output feature supported enabled)
  if(supported)
    set(state supported)
  else()
    set(state unsupported)
  endif()
  set(${output} "\"${feature}\":{\"supported\":${supported},\"enabled\":${enabled},\"state\":\"${state}\"}" PARENT_SCOPE)
endfunction()

function(laghu_configure_hardening)
  if(CMAKE_BUILD_TYPE STREQUAL "Release")
    set(release_build true)
  else()
    set(release_build false)
  endif()
  if(UNIX)
    set(posix_build true)
  else()
    set(posix_build false)
  endif()
  if(UNIX AND NOT CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    set(elf_build true)
  else()
    set(elf_build false)
  endif()

  if(posix_build)
    if(elf_build)
      laghu_hardening_probe(pie pie_supported
        COMPILE_OPTIONS -fPIE
        LINK_OPTIONS -pie)
    else()
      laghu_hardening_probe(pie pie_supported COMPILE_OPTIONS -fPIE)
    endif()
    laghu_hardening_probe(stack_protection stack_protection_supported
      COMPILE_OPTIONS -fstack-protector-strong)
    laghu_hardening_probe(fortification fortification_supported
      SOURCE "${CMAKE_SOURCE_DIR}/tests/hardening/probes/fortification.cpp"
      COMPILE_OPTIONS -O2 -D_FORTIFY_SOURCE=3)
  else()
    set(pie_supported false)
    set(stack_protection_supported false)
    set(fortification_supported false)
  endif()
  if(elf_build)
    laghu_hardening_probe(relro relro_supported LINK_OPTIONS -Wl,-z,relro)
    laghu_hardening_probe(immediate_binding immediate_binding_supported LINK_OPTIONS -Wl,-z,now)
  else()
    set(relro_supported false)
    set(immediate_binding_supported false)
  endif()

  if(release_build AND posix_build)
    if(NOT pie_supported)
      laghu_hardening_fail("feature=pie; required=release_posix")
    endif()
    if(NOT stack_protection_supported)
      laghu_hardening_fail("feature=stack_protection; required=release_posix")
    endif()
  endif()
  if(release_build AND elf_build)
    if(NOT relro_supported)
      laghu_hardening_fail("feature=relro; required=release_elf")
    endif()
    if(NOT immediate_binding_supported)
      laghu_hardening_fail("feature=immediate_binding; required=release_elf")
    endif()
  endif()

  set(common_compile_options)
  set(executable_compile_options)
  set(link_options)
  set(executable_link_options)
  if(release_build)
    if(posix_build AND pie_supported)
      list(APPEND executable_compile_options -fPIE)
      if(elf_build)
        list(APPEND executable_link_options -pie)
      endif()
      set(pie_enabled true)
    else()
      set(pie_enabled false)
    endif()
    if(posix_build AND stack_protection_supported)
      list(APPEND common_compile_options -fstack-protector-strong)
      set(stack_protection_enabled true)
    else()
      set(stack_protection_enabled false)
    endif()
    if(elf_build AND relro_supported)
      list(APPEND link_options -Wl,-z,relro)
      set(relro_enabled true)
    else()
      set(relro_enabled false)
    endif()
    if(elf_build AND immediate_binding_supported)
      list(APPEND link_options -Wl,-z,now)
      set(immediate_binding_enabled true)
    else()
      set(immediate_binding_enabled false)
    endif()
    if(posix_build AND fortification_supported)
      list(APPEND common_compile_options -O2 -D_FORTIFY_SOURCE=3)
      set(fortification_enabled true)
    else()
      set(fortification_enabled false)
    endif()
  else()
    set(pie_enabled false)
    set(stack_protection_enabled false)
    set(relro_enabled false)
    set(immediate_binding_enabled false)
    set(fortification_enabled false)
  endif()

  laghu_hardening_feature_json(pie_json pie "${pie_supported}" "${pie_enabled}")
  laghu_hardening_feature_json(stack_protection_json stack_protection "${stack_protection_supported}" "${stack_protection_enabled}")
  laghu_hardening_feature_json(relro_json relro "${relro_supported}" "${relro_enabled}")
  laghu_hardening_feature_json(immediate_binding_json immediate_binding "${immediate_binding_supported}" "${immediate_binding_enabled}")
  laghu_hardening_feature_json(fortification_json fortification "${fortification_supported}" "${fortification_enabled}")
  set(metadata "{\"mode\":\"${CMAKE_BUILD_TYPE}\",${pie_json},${stack_protection_json},${relro_json},${immediate_binding_json},${fortification_json}}")

  set(LAGHU_HARDENING_COMPILE_OPTIONS "${common_compile_options}" CACHE INTERNAL
    "Laghu common hardening compile options" FORCE)
  set(LAGHU_HARDENING_EXECUTABLE_COMPILE_OPTIONS "${executable_compile_options}" CACHE INTERNAL
    "Laghu executable hardening compile options" FORCE)
  set(LAGHU_HARDENING_LINK_OPTIONS "${link_options}" CACHE INTERNAL
    "Laghu linkable hardening options" FORCE)
  set(LAGHU_HARDENING_EXECUTABLE_LINK_OPTIONS "${executable_link_options}" CACHE INTERNAL
    "Laghu executable hardening link options" FORCE)
  set(LAGHU_HARDENING_METADATA_JSON "${metadata}" CACHE INTERNAL "Laghu hardening metadata" FORCE)
endfunction()
