# SPDX-License-Identifier: AGPL-3.0-only
include_guard(GLOBAL)

# This module is the sole declaration of Laghu's feature vocabulary.  It
# deliberately records provider and external dependency requirements without
# finding them: source/link modes and version gates are configured by later
# build-configuration tasks.
set(LAGHU_FEATURE_IDS
  core
  tls
  http2
  http3
  structured_data
  async_dns
  regex
  compression_zlib
  compression_brotli
  compression_zstd
  geoip)

function(laghu_declare_feature id)
  cmake_parse_arguments(PARSE_ARGV 1 feature
    "REQUIRED"
    ""
    "DEPENDS;CONFLICTS;EXTERNAL_DEPENDENCIES;PROVIDERS")
  list(FIND LAGHU_FEATURE_IDS "${id}" id_index)
  if(id_index EQUAL -1)
    message(FATAL_ERROR "Laghu feature registry failed: feature=${id} rule=undeclared_feature")
  endif()
  if(feature_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "Laghu feature registry failed: feature=${id} rule=invalid_declaration")
  endif()
  set_property(GLOBAL PROPERTY "LAGHU_FEATURE_REQUIRED_${id}" "${feature_REQUIRED}")
  set_property(GLOBAL PROPERTY "LAGHU_FEATURE_DEPENDS_${id}" "${feature_DEPENDS}")
  set_property(GLOBAL PROPERTY "LAGHU_FEATURE_CONFLICTS_${id}" "${feature_CONFLICTS}")
  set_property(GLOBAL PROPERTY "LAGHU_FEATURE_EXTERNAL_DEPENDENCIES_${id}" "${feature_EXTERNAL_DEPENDENCIES}")
  set_property(GLOBAL PROPERTY "LAGHU_FEATURE_PROVIDERS_${id}" "${feature_PROVIDERS}")
endfunction()

function(laghu_feature_require_known id rule)
  list(FIND LAGHU_FEATURE_IDS "${id}" id_index)
  if(id_index EQUAL -1)
    message(FATAL_ERROR "Laghu feature registry failed: feature=${id} rule=${rule}")
  endif()
endfunction()

function(laghu_feature_property id name output)
  laghu_feature_require_known("${id}" unknown_feature)
  get_property(value GLOBAL PROPERTY "LAGHU_FEATURE_${name}_${id}")
  set(${output} "${value}" PARENT_SCOPE)
endfunction()

function(laghu_feature_registry_initialize)
  laghu_declare_feature(core REQUIRED)
  laghu_declare_feature(tls PROVIDERS OPENSSL LIBRESSL)
  laghu_declare_feature(http2 EXTERNAL_DEPENDENCIES nghttp2)
  # HTTP/3 depends on TLS but intentionally does not depend on HTTP/2: h3 and
  # h2c are independent protocol capabilities.
  laghu_declare_feature(http3 DEPENDS tls EXTERNAL_DEPENDENCIES ngtcp2 nghttp3)
  laghu_declare_feature(structured_data EXTERNAL_DEPENDENCIES yyjson)
  laghu_declare_feature(async_dns EXTERNAL_DEPENDENCIES c-ares)
  laghu_declare_feature(regex EXTERNAL_DEPENDENCIES pcre2_8bit)
  laghu_declare_feature(compression_zlib EXTERNAL_DEPENDENCIES zlib_ng)
  laghu_declare_feature(compression_brotli EXTERNAL_DEPENDENCIES brotli)
  laghu_declare_feature(compression_zstd EXTERNAL_DEPENDENCIES zstd)
  laghu_declare_feature(geoip EXTERNAL_DEPENDENCIES libmaxminddb)
endfunction()

function(laghu_feature_validate_registry)
  foreach(feature IN LISTS LAGHU_FEATURE_IDS)
    foreach(name IN ITEMS DEPENDS CONFLICTS)
      laghu_feature_property("${feature}" "${name}" values)
      foreach(value IN LISTS values)
        laghu_feature_require_known("${value}" "${name}")
        if(value STREQUAL feature)
          message(FATAL_ERROR
            "Laghu feature registry failed: feature=${feature} ${name}=${value} rule=self_reference")
        endif()
      endforeach()
    endforeach()
  endforeach()
endfunction()

function(laghu_feature_visit feature)
  get_property(state GLOBAL PROPERTY "LAGHU_FEATURE_VISIT_${feature}")
  if(state STREQUAL visiting)
    message(FATAL_ERROR "Laghu feature registry failed: feature=${feature} rule=dependency_cycle")
  endif()
  if(state STREQUAL done)
    return()
  endif()
  set_property(GLOBAL PROPERTY "LAGHU_FEATURE_VISIT_${feature}" visiting)
  laghu_feature_property("${feature}" DEPENDS dependencies)
  foreach(dependency IN LISTS dependencies)
    get_property(dependency_state GLOBAL PROPERTY "LAGHU_FEATURE_VISIT_${dependency}")
    if(dependency_state STREQUAL visiting)
      message(FATAL_ERROR
        "Laghu feature registry failed: feature=${feature} dependency=${dependency} rule=dependency_cycle")
    endif()
    laghu_feature_visit("${dependency}")
  endforeach()
  set_property(GLOBAL PROPERTY "LAGHU_FEATURE_VISIT_${feature}" done)
  get_property(effective GLOBAL PROPERTY LAGHU_FEATURE_EFFECTIVE_WORKING)
  list(APPEND effective "${feature}")
  set_property(GLOBAL PROPERTY LAGHU_FEATURE_EFFECTIVE_WORKING "${effective}")
endfunction()

function(laghu_resolve_features output)
  cmake_parse_arguments(PARSE_ARGV 1 selection "" "DIAGNOSTIC_PREFIX" "REQUESTED;AVAILABLE")
  if(selection_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "Laghu feature registry failed: rule=invalid_selection")
  endif()
  laghu_feature_validate_registry()

  set(requested ${selection_REQUESTED})
  list(FIND requested core core_requested)
  if(core_requested EQUAL -1)
    list(INSERT requested 0 core)
  endif()
  set(seen)
  foreach(feature IN LISTS requested)
    list(FIND LAGHU_FEATURE_IDS "${feature}" feature_index)
    if(feature_index EQUAL -1)
      if(selection_DIAGNOSTIC_PREFIX)
        message(FATAL_ERROR
          "${selection_DIAGNOSTIC_PREFIX}: feature=${feature} rule=unknown_feature")
      endif()
      laghu_feature_require_known("${feature}" unknown_feature)
    endif()
    list(FIND seen "${feature}" duplicate_index)
    if(NOT duplicate_index EQUAL -1)
      if(selection_DIAGNOSTIC_PREFIX)
        message(FATAL_ERROR
          "${selection_DIAGNOSTIC_PREFIX}: feature=${feature} rule=duplicate_request")
      endif()
      message(FATAL_ERROR "Laghu feature registry failed: feature=${feature} rule=duplicate_request")
    endif()
    list(APPEND seen "${feature}")
  endforeach()
  foreach(feature IN LISTS selection_AVAILABLE)
    laghu_feature_require_known("${feature}" unknown_available_feature)
  endforeach()

  foreach(feature IN LISTS LAGHU_FEATURE_IDS)
    set_property(GLOBAL PROPERTY "LAGHU_FEATURE_VISIT_${feature}" "")
  endforeach()
  set_property(GLOBAL PROPERTY LAGHU_FEATURE_EFFECTIVE_WORKING "")
  foreach(feature IN LISTS requested)
    laghu_feature_visit("${feature}")
  endforeach()
  get_property(effective GLOBAL PROPERTY LAGHU_FEATURE_EFFECTIVE_WORKING)
  list(REMOVE_DUPLICATES effective)

  foreach(feature IN LISTS effective)
    list(FIND selection_AVAILABLE "${feature}" available_index)
    if(available_index EQUAL -1)
      if(selection_DIAGNOSTIC_PREFIX)
        message(FATAL_ERROR
          "${selection_DIAGNOSTIC_PREFIX}: feature=${feature} rule=feature_unavailable")
      endif()
      message(FATAL_ERROR "Laghu feature registry failed: feature=${feature} rule=feature_unavailable")
    endif()
    laghu_feature_property("${feature}" CONFLICTS conflicts)
    foreach(conflict IN LISTS conflicts)
      list(FIND effective "${conflict}" conflict_index)
      if(NOT conflict_index EQUAL -1)
        if(selection_DIAGNOSTIC_PREFIX)
          message(FATAL_ERROR
            "${selection_DIAGNOSTIC_PREFIX}: feature=${feature} conflict=${conflict} rule=feature_conflict")
        endif()
        message(FATAL_ERROR
          "Laghu feature registry failed: feature=${feature} conflict=${conflict} rule=feature_conflict")
      endif()
    endforeach()
  endforeach()
  set(${output} "${effective}" PARENT_SCOPE)
endfunction()

function(laghu_feature_target_name feature output)
  laghu_feature_require_known("${feature}" unknown_feature)
  set(${output} "laghu_feature_${feature}" PARENT_SCOPE)
endfunction()

function(laghu_feature_json_array output)
  if(ARGN)
    list(JOIN ARGN "\", \"" members)
    set(${output} "[\"${members}\"]" PARENT_SCOPE)
  else()
    set(${output} "[]" PARENT_SCOPE)
  endif()
endfunction()

function(laghu_materialize_feature_targets)
  foreach(feature IN LISTS ARGN)
    laghu_feature_target_name("${feature}" target)
    if(NOT TARGET "${target}")
      add_library("${target}" INTERFACE)
      set_property(TARGET "${target}" PROPERTY LAGHU_FEATURE_ID "${feature}")
    endif()
  endforeach()
  foreach(feature IN LISTS ARGN)
    laghu_feature_target_name("${feature}" target)
    laghu_feature_property("${feature}" DEPENDS dependencies)
    foreach(dependency IN LISTS dependencies)
      list(FIND ARGN "${dependency}" dependency_enabled)
      if(dependency_enabled EQUAL -1)
        message(FATAL_ERROR
          "Laghu feature registry failed: feature=${feature} dependency=${dependency} rule=unresolved_dependency")
      endif()
      laghu_feature_target_name("${dependency}" dependency_target)
      target_link_libraries("${target}" INTERFACE "${dependency_target}")
    endforeach()
  endforeach()
endfunction()

function(laghu_write_feature_registry_metadata output requested effective available)
  set(feature_members)
  foreach(feature IN LISTS LAGHU_FEATURE_IDS)
    laghu_feature_property("${feature}" REQUIRED required)
    laghu_feature_property("${feature}" DEPENDS depends)
    laghu_feature_property("${feature}" CONFLICTS conflicts)
    laghu_feature_property("${feature}" EXTERNAL_DEPENDENCIES external_dependencies)
    laghu_feature_property("${feature}" PROVIDERS providers)
    laghu_feature_json_array(depends_json ${depends})
    laghu_feature_json_array(conflicts_json ${conflicts})
    laghu_feature_json_array(external_dependencies_json ${external_dependencies})
    laghu_feature_json_array(providers_json ${providers})
    if(required)
      set(required_json true)
    else()
      set(required_json false)
    endif()
    list(APPEND feature_members
      "    \"${feature}\": {\"required\": ${required_json}, \"depends\": ${depends_json}, \"conflicts\": ${conflicts_json}, \"external_dependencies\": ${external_dependencies_json}, \"providers\": ${providers_json}}")
  endforeach()
  list(JOIN feature_members ",\n" rendered_features)
  laghu_feature_json_array(requested_json ${requested})
  laghu_feature_json_array(effective_json ${effective})
  laghu_feature_json_array(available_json ${available})
  file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/config")
  file(WRITE "${output}"
"{\n  \"schema_version\": \"laghu-feature-registry-v1\",\n  \"requested\": ${requested_json},\n  \"effective\": ${effective_json},\n  \"available\": ${available_json},\n  \"features\": {\n${rendered_features}\n  }\n}\n")
endfunction()

function(laghu_configure_feature_registry)
  cmake_parse_arguments(PARSE_ARGV 0 configuration "" "DIAGNOSTIC_PREFIX" "REQUESTED;AVAILABLE")
  if(configuration_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "Laghu feature registry failed: rule=invalid_configuration")
  endif()
  laghu_feature_registry_initialize()
  laghu_resolve_features(effective
    REQUESTED ${configuration_REQUESTED}
    AVAILABLE ${configuration_AVAILABLE}
    DIAGNOSTIC_PREFIX "${configuration_DIAGNOSTIC_PREFIX}")
  laghu_materialize_feature_targets(${effective})
  set(LAGHU_REQUESTED_FEATURES "${configuration_REQUESTED}" CACHE INTERNAL "Laghu requested features")
  set(LAGHU_EFFECTIVE_FEATURES "${effective}" CACHE INTERNAL "Laghu effective features")
  set(LAGHU_AVAILABLE_FEATURES "${configuration_AVAILABLE}" CACHE INTERNAL "Laghu available features")
  set(metadata "${CMAKE_BINARY_DIR}/config/laghu-feature-registry-v1.json")
  laghu_write_feature_registry_metadata("${metadata}" "${configuration_REQUESTED}" "${effective}" "${configuration_AVAILABLE}")
  set(LAGHU_FEATURE_REGISTRY_METADATA "${metadata}" CACHE INTERNAL "Laghu feature registry metadata")
endfunction()
