# SPDX-License-Identifier: AGPL-3.0-only
if(NOT DEFINED MODULE OR NOT DEFINED LAGHU_SOURCE OR NOT DEFINED FIXTURE)
  message(FATAL_ERROR "Laghu API boundary runner requires MODULE, LAGHU_SOURCE, and FIXTURE")
endif()
include("${MODULE}")
get_filename_component(fixture_name "${FIXTURE}" NAME)
if(fixture_name STREQUAL "legacy-global-symbol")
  laghu_validate_implementation_source("${FIXTURE}/source.cpp")
elseif(fixture_name STREQUAL "cross-private-source")
  laghu_validate_private_header_ownership("${FIXTURE}/source.cpp" proxy)
elseif(fixture_name STREQUAL "direct-private-path")
  laghu_validate_private_header_ownership("${FIXTURE}/source.cpp" core)
elseif(fixture_name STREQUAL "private-namespace")
  laghu_api_validate_header_file("${FIXTURE}/header.hpp" core private)
else()
  laghu_api_validate_header_file("${FIXTURE}/header.hpp" core contract)
endif()
